server:
  port: 8083
# 方便调试
logging:
  level:
    org.springframework.web: trace
    org.springframework.security: trace
    org.springframework.security.oauth2: debug
spring:
  profiles:
    active: sas